### PR TITLE
Bugfix: send proper unsubscribe message to the websocket

### LINKED ISSUE #72: Unsubscribe broken, sends bogus data
```
const Client = require('./').Client


const client = new Client({
    hostname: 'localhost',
    port: 3000,
    useTLS: false
})
client.on('connectionInfo', x => console.log(x))
client.connect().then(() =>
    client.subscribe({
        context: 'vessels.self',
        subscribe: [{ path: 'navigation.position' }]
    }, 'a')
).then(() =>
    client.subscribe({
        context: 'vessels.self',
        subscribe: [{ path: 'navigation.speedOverGround' }]
    }, 'b')
).then(s => {
    s.unsubscribe()
}).catch(e => console.error(e))
```

results in this written to the socket:

`{"context":"vessels.dont_send_me_anything","subscribe":[{"path":"dont_send_me_anything.dont_send_me_anything"}],"format":"delta","policy":"instant"}`

### PR DESCRIPTION
**Pull request by fabdrol**
Fixes #72

### CODE REVIEW

File: dist/lib/connection.js [hunk 1]
```diff
@@ -203,7 +203,9 @@ class Connection extends _eventemitter.default {
   }
 
   initiateSocket() {
-    this.socket = new _isomorphicWs.default(this.wsURI);
+    this.socket = new _isomorphicWs.default(this.wsURI, this.options.rejectUnauthorized === false ? {
```
Comment (tkurki) [inline dist/lib/connection.js:206]: How is this related? No changes in src/lib/connection.js

Comment (fabdrol) [reply dist/lib/connection.js:206]: @tkurki I reckon that the last time I pushed to master (PR or otherwise) no dist was made. Having said that; any changes to the `dist` folder can be ignored -- as long as `src` is good dist will follow. I'll look at the build scripts to make that more automated

Comment (fabdrol) [reply dist/lib/connection.js:206]: Probably a commit hook to build before commit would be useful here

**Comment by fabdrol** [comment]
@tkurki I'd like to merge, agreed?
